# Generated by Django 4.0.1 on 2022-01-20 06:23

from django.db import migrations, models
import management_system.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, unique=True, verbose_name='Company Name')),
                ('person_name', models.CharField(max_length=32, unique=True, verbose_name='Person')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('hardware_count', models.PositiveIntegerField(default=0, verbose_name='Hardware Count')),
                ('ip_address', models.CharField(default='', max_length=32, verbose_name='IP Address')),
                ('uuid', models.CharField(default=management_system.utils.generate_uuid, max_length=64, unique=True, verbose_name='Person')),
            ],
        ),
    ]
